/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package topic5;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author usuario
 */
public class Consulta extends javax.swing.JFrame {

 private static String bd="highschool";
 private static String user="root";
 private static String password="root";
 private static String host="localhost";
 private static String server="jdbc:mysql://"+host+"/"+bd;
 static Statement st;
 static ResultSet rs;
 
 Connect c = new Connect();
 Connection cn = c.connection();
    public Consulta() {
        initComponents();
        
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_course = new javax.swing.JComboBox();
        btn_cargar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_student = new javax.swing.JButton();
        txt_student = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Course Name");

        cmb_course.setName("cmb_course"); // NOI18N
        cmb_course.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_courseItemStateChanged(evt);
            }
        });
        cmb_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_courseActionPerformed(evt);
            }
        });

        btn_cargar.setText("Listar");
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });

        jLabel2.setText("Student Number:");

        btn_student.setText("Buscar Notas");
        btn_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentActionPerformed(evt);
            }
        });

        txt_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_student, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_student))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_course, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cargar)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cargar))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_student))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_courseActionPerformed
   // getStudents();        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_courseActionPerformed

    private void cmb_courseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_courseItemStateChanged
        
    }//GEN-LAST:event_cmb_courseItemStateChanged

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
getStudentsXCourse();       
    }//GEN-LAST:event_btn_cargarActionPerformed

    private void btn_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentActionPerformed
     
      
     int student = Integer.parseInt(txt_student.getText());
     getFinalNotes(student);
    }//GEN-LAST:event_btn_studentActionPerformed

    private void txt_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentActionPerformed

    /**
     * @param args the command line arguments
     */
    public void getFinalNotes(int student){
        String query = "Select nc.student, course_name, final from notesxcourse nc join student s "
                + "on nc.student=s.reg_number and s.reg_number="+student+" order by nc.final desc ";
        String result = "Final notes for student number "+student+"\n";
     try {
         st = cn.createStatement();
         rs = st.executeQuery(query);
         while (rs.next()) {

				String course = rs.getString(2);
				int finalNote = rs.getInt(3);
				 result += (course + " " + finalNote+"\n");
     }
     }catch (SQLException ex) {
         Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
     }
     System.out.println(result);
    }
    public void getStudentsXCourse(){
         String course = cmb_course.getSelectedItem().toString();
        String str = "Course name: " + course + "\n";
         String student="";
         String teacher = "";
       try {
           
           
            st = cn.createStatement();
            String query = "Select s.first_name, s.last_name, c.name, t.first_name,"
                    + "t.last_name from course c JOIN studentxcourse sc on "
                    + "sc.course_name = c.name join teacher t on t.license = c.teacher "
                    + "join student s on s.reg_number = sc.student and c.name = "+"'"+course+"' "
                    + "order by s.last_name";
            rs = st.executeQuery(query);
            
          
            while (rs.next()){
               
                student += rs.getString(2) +" "+ rs.getString(1)+ "\n";
                teacher = rs.getString(5) +" "+ rs.getString(4);
            
            }
            String res = str + "Teacher: " + teacher + "\n" +
                    "Students: "+ "\n" +student;
           System.out.println(res);
         //   System.out.println(teacher);
        } catch (SQLException ex) {
            System.out.println("Imposible realizar conexion con "+server+" ... FAIL");
            //Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex)
        }
        
    } 
    
    public void cargarCombo(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("Select name from course");
            while (rs.next()){
               cmb_course.addItem(rs.getString(1));
            }
          
        } catch (SQLException ex) {
            System.out.println("Imposible realizar conexion con "+server+" ... FAIL");
            //Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex)
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
    /*     try {
            Class.forName("com.mysql.jdbc.Driver");
           connection = DriverManager.getConnection(server,user,password);

            System.out.println("Conexión a base de datos "+server+" ... OK");
            st = connection.createStatement();
            rs = st.executeQuery("Select name from course");
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Error cargando el Driver MySQL JDBC ... FAIL");
            //Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.out.println("Imposible realizar conexion con "+server+" ... FAIL");
            //Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex)
        }
            */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargar;
    private javax.swing.JButton btn_student;
    private javax.swing.JComboBox cmb_course;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_student;
    // End of variables declaration//GEN-END:variables
}
